
# This file defines dbt profiles for deployed dbt jobs.
dbt_sql:
   target: dev # default target
   outputs:

    # Doing local development with the dbt CLI?
    # Then you should create your own profile in your .dbt/profiles.yml using 'dbt init'
    # (See README.md)

    # The default target when deployed with the Databricks CLI
    # N.B. when you use dbt from the command line, it uses the profile from .dbt/profiles.yml
    dev:
      type: databricks
      method: http
      catalog: haley_source_ws
      schema: default
      http_path: /sql/1.0/warehouses/61b2ae8974016fcd
      # The workspace host / token are provided by Databricks
      # see databricks.yml for the workspace host used for 'dev'
      host: {{ host }}
      token: {{ token }}

    # The production target when deployed with the Databricks CLI
    prod:
      type: databricks
      method: http
      catalog: haley_source_ws
      schema: default
      http_path: /sql/1.0/warehouses/61b2ae8974016fcd
      # The workspace host / token are provided by Databricks
      # see databricks.yml for the workspace host used for 'prod'
      host: "{{ env_var('DBT_HOST') }}"
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
